### PR TITLE
Added vendor.conf parsing

### PR DESCRIPTION
**Pull request by albert7c**

### CODE REVIEW

**Comment by albert7c** [comment]
Screen Shot 2019-07-17 at 9 11 32 PM

**Comment by albert7c** [comment]
Screen Shot 2019-07-17 at 9 24 58 PM

**Comment by mjpitz** [comment]
So in the go graph, the organization is actually the authority of the URL while the module is that path.. e.g. org="github.com" module="testOrganization/testModule". Many companies set up their own vanity URL's because they want monitoring around usage of their modules so you go get something like "oss.indeed.com/go/go-groups" instead of "github.com/indeedeng/go-groups".

**Comment by albert7c** [comment]
Screen Shot 2019-07-19 at 9 41 20 PM

**Comment by mjpitz** [comment]
Resolves #20

**Pull request merged**
